require 'zahry/keymaps'
require 'zahry/options'
require 'zahry/lazy'
require 'zahry/colorscheme'
require 'zahry.plugins.resizeSplits'
require 'zahry.macros.ui-test'
require 'zahry.utils.db'
-- require 'zahry/snippets'
