# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=eDP-1,highres,auto-down,1
# monitor=HDMI-A-1,highres,auto-up,1
monitor=eDP-1,highres,auto-left,1.25
monitor=HDMI-A-1,highres,auto-right,1

# exec-once = [workspace 2 silent] $browser
# exec-once = [workspace 3 silent] slack
# exec-once = [workspace 4 silent] datagrip
# exec-once = [workspace 4 silent] postman

exec-once = handle_monitor_connect.sh

# windowrule = float,  title:^(GAMEDEV)
# windowrule = center, title:^(GAMEDEV)
