gui:
  sidePanelWidth: 0.3

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  allowEmptyCommits: true

customCommands:
  - key: 'E'
    description: 'Add empty commit'
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'Commit message'
        key: 'CommitMessage'
        initialValue: ''
    command: "git commit --allow-empty -m '{{.Form.CommitMessage}}'"
    loadingText: 'Committing empty commit...'
  - key: '<c-c>'
    context: 'global'
    prompts:
      - type: 'menu'
        title: 'What kind of commit is this'
        key: 'CommitType'
        options:
          - name: 'feature'
            description: 'a feature'
            value: 'feat'
          - name: 'fix'
            description: 'a fix'
            value: 'fix'
          - name: 'chore'
            description: 'a chore'
            value: 'chore'
          - name: 'docs'
            description: 'a doc'
            value: 'docs'
          - name: 'refactor'
            description: 'a refactor'
            value: 'refactor'
          - name: 'test'
            description: 'a test'
            value: 'test'
          - name: 'build'
            description: 'a build'
            value: 'build'
      - type: 'input'
        title: 'What is the ticket this refers to'
        key: 'Ticket'
        initialValue: ''
      - type: 'input'
        title: 'Commit subject'
        key: 'CommitSubject'
        initialValue: ''
    command: "git commit -m '{{.Form.CommitType}}: {{.Form.Ticket}} - {{.Form.CommitSubject}}'"
    loadingText: 'Committing changes...'
