gui:
  sidePanelWidth: 0.3
  showFileIcons: true
  nerdFontsVersion: "3"

git:
  pagers:
    - pager: delta --dark --paging=never
      colorArg: always
  allowEmptyCommits: true

customCommands:
  - key: 'E'
    description: 'Add empty commit'
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'Commit message'
        key: 'CommitMessage'
        initialValue: ''
    command: "git commit --allow-empty -m '{{.Form.CommitMessage}}'"
    loadingText: 'Committing empty commit...'
  - key: '<c-w>'
    context: 'global'
    description: 'Create MR/PR (GitLab/GitHub)'
    prompts:
      - type: 'menu'
        title: 'Where do you want to publish this?'
        key: 'Provider'
        options:
          - name: 'gitlab'
            description: 'Gitlab a merge request'
            value: 'gitlab'
          - name: 'github'
            description: 'Microsoft a pull request'
            value: 'github'
      - type: 'menu'
        title: 'How do you want to finish this?'
        key: 'Flow'
        options:
          - name: 'generate in CLI'
            description: 'Autofill from commits and submit from terminal'
            value: 'cli'
          - name: 'finish in web'
            description: 'Open browser to complete creation'
            value: 'web'

    command: >
      {{- if eq .Form.Provider "gitlab" -}}
        glab mr create{{if eq .Form.Flow "web"}} --web{{else}} --fill --fill-commit-body --squash-before-merge --yes{{end}}
      {{- else -}}
        gh pr create{{if eq .Form.Flow "web"}} --web{{else}} --fill{{end}}
      {{- end -}}
    loadingText: 'Creating PR/MR…'
    output: terminal
