require 'zahry.plugins.lualine'
require 'zahry.plugins.gitplugs'
require 'zahry.plugins.whichkey'
require 'zahry.plugins.colorscheme'
require 'zahry.plugins.harpoon'
require 'zahry.plugins.cmp'
require 'zahry.plugins.conform'
require 'zahry.plugins.mini'
-- require 'zahry.plugins.telescope'
require 'zahry.plugins.lsp'
