require 'zahry/plugins/colorscheme'
require 'zahry/plugins/gitplugs'
require 'zahry/plugins/telescope'
require 'zahry/plugins/whichkey'
require 'zahry/plugins/lsp'
require 'zahry/plugins/conform'
require 'zahry/plugins/lualine'
require 'zahry/plugins/mini'
require 'zahry/plugins/cmp'
require 'zahry/plugins/oil'
require('Comment').setup()
