"$schema" = 'https://starship.rs/config-schema.json'

palette = 'oldworld'
add_newline = true

# Custom format to show username@hostname before directory
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

# # Move programming languages, package info, and timing to the right side
right_format = """
$nix_shell"""
# $package\
# $c\
# $cpp\
# $bun\
# $cmake\
# $conan\
# $daml\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $golang\
# $guix_shell\
# $haskell\
# $haxe\
# $helm\
# $java\
# $julia\
# $kotlin\
# $gradle\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $opa\
# $perl\
# $php\
# $pulumi\
# $purescript\
# $python\
# $raku\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $solidity\
# $swift\
# $terraform\
# $typst\
# $vlang\
# $vagrant\
# $zig\
# $buf\
# $conda\
# $meson\
# $spack\
# $crystal\
# $hg_branch\
# $pijul_channel\
# $docker_context\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $env_var\
# $custom\
# $sudo"""

[palettes.gruvbox_dark]
color_fg0 = '#dce3e8'
color_bg1 = '#101920'
color_bg3 = '#665c54'
color_blue = '#185d92'
color_aqua = '#b3e2f3'
color_green = '#6c8b4c'
color_orange = '#d65d0e'
color_purple = '#a58caa'
color_red = '#a14e3e'
color_yellow = '#cbb86c'

[palettes.slavana]
color_fg0 = '#dce3e8'
color_bg1 = '#101920'
color_bg3 = '#1a1a1a'
color_blue = '#185d92'
color_aqua = '#89c7da'
color_green = '#6c8b4c'
color_orange = '#d65d0e'
color_purple = '#a58caa'
color_red = '#a14e3e'
color_yellow = '#cbb86c'

[palettes.oldworld]
color_fg0 = '#c9c7cd'
color_bg1 = '#161617'
color_bg3 = '#27272a'
color_blue = '#9ca2cf'
color_aqua = '#85b5ba'
color_green = '#90b99f'
color_purple = '#e29eca'
color_red = '#ea83a5'
color_yellow = '#e6b99d'
color_orange = '#e6b99d'
color_white = '#c9c7cd'
color_gray = '#27272a'

[palettes.blu]
color_fg0 = '#dce3e8'
color_bg1 = '#101920'
color_bg3 = '#3a3a3a'
color_blue = '#185d92'
color_blue_light = '#3f91c1'
color_aqua = '#89c7da'
color_cyan = '#89c7da'
color_cyan_light = '#b3e2f3'
color_green = '#6c8b4c'
color_green_light = '#9dbb70'
color_orange = '#d65d0e'
color_purple = '#a58caa'
color_purple_light = '#c0a7c6'
color_red = '#a14e3e'
color_red_light = '#e0745e'
color_yellow = '#cbb86c'
color_yellow_light = '#f1dc87'
color_white = '#e8f0f4'
color_comment = '#7c8488'

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
read_only = " 󰌾"
style = "bold green"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
ssh_only = false
format = "[@](bold color_green)[$hostname]($style)[\\]](color_red) [➜](color_yellow) "
style = "bold color_aqua"

[username]
style_user = "bold color_blue"
style_root = "bold color_red"
format = "[\\[](color_red)[$user]($style)"
show_always = true

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = "[$symbol$version]($style) "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
