"$schema" = 'https://starship.rs/config-schema.json'

palette = 'slavana'

[palettes.gruvbox_dark]
color_fg0 = '#dce3e8'
color_bg1 = '#101920'
color_bg3 = '#665c54'
color_blue = '#185d92'
color_aqua = '#b3e2f3'
color_green = '#6c8b4c'
color_orange = '#d65d0e'
color_purple = '#a58caa'
color_red = '#a14e3e'
color_yellow = '#cbb86c'

[palettes.slavana]
color_fg0 = '#dce3e8'
color_bg1 = '#101920'
color_bg3 = '#1a1a1a'
color_blue = '#185d92'
color_aqua = '#89c7da'
color_green = '#6c8b4c'
color_orange = '#d65d0e'
color_purple = '#a58caa'
color_red = '#a14e3e'
color_yellow = '#cbb86c'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
NixOS = "󰌽"
