#!/bin/bash
source "$HOME/.dotfiles/.env"

SCRIPTS=("connect headphones" "disconnect headphones" )

declare -A SCRIPT_COMMAND_MAP=(
  ["connect headphones"]="bluetoothctl connect $HEADPHONE_MAC"
  ["disconnect headphones"]="bluetoothctl disconnect $HEADPHONE_MAC"
)

DESIRED_SCRIPT="$(printf '%s\n' "${SCRIPTS[@]}" | rofi -dmenu -p "Choose an option")"

cmd=${SCRIPT_COMMAND_MAP["$DESIRED_SCRIPT"]}
if [[ -n "$cmd" ]]; then
  eval "$cmd"
fi
