#!/bin/bash

LAYOUTS=("master" "dwindle" "scrolling")
DESIRED_LAYOUT="$(printf '%s\n' "${LAYOUTS[@]}" | rofi -dmenu -p "Choose an option")"

if [[ -n "$DESIRED_LAYOUT" ]]; then
  hyprctl eval "hl.config({ general = { layout = \"${DESIRED_LAYOUT}\" } })"
fi
