#!/bin/bash

PID_FILE=/tmp/screen_record_ffmpeg.pid

if [[ -f "$PID_FILE" ]] && ps -p "$(cat "$PID_FILE")" > /dev/null; then
    now=$(date +%s)
    file_time=$(stat -c %Y "$PID_FILE")
    diff=$((now - file_time))
    printf '🛑 %02d:%02d:%02d\n' $((diff/3600)) $(((diff%3600)/60)) $((diff%60))
fi
