# Colorscheme
# import = [
#     "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
# ]

[window]
decorations = "None"
padding = { x = 4, y =8 }
blur = true
opacity = 0.7
dynamic_padding = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
]

[font]
size = 7

[env]
WINIT_X11_SCALE_FACTOR=1
