# Colorscheme
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
decorations = "None"
padding = { x = 4, y =8 }
blur = true
opacity = 0.85
dynamic_padding = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
]

[font]
size = 12
